### PR TITLE
quick ab stress test, 1000 signatures, 500 concurrent 'signatories'

### PR DESCRIPTION
**Pull request by tttp**
Hi @marcinkoziej, could you run it on your dev instance on your laptop? (change the url of the server in the script, obviously)

Curious to see how long it takes to process 1k signatures

Also, with dedupe on, we'll need to switch to a better loadtest tools ;)

### CODE REVIEW

**Comment by marcinkoziej** [comment]
I'll do that tomorrow.

For dedupe, I was thinking that we could go this async, that is store the signature and return OK to widget.
Later in background process it in various ways - e.g. for sigs:

- drop dupes
- send confirmation email (only for non dupe)
- wait for confirmation

Or for pledges
- send confirmation
- wait for confirmation
- update dupes

Wysłano z aplikacji ProtonMail

-------- Oryginalna wiadomość --------
‎ 5 mar 2020, 10:32, xavier dutoit napisał(a):

**Comment by tttp** [comment]
So we need to
1. Be able to dedupe encrypted signatures
2. Be able to have per campaign dedupe rules (eg one dedupe on email, the
other on name +email, the 3rd on an I'd, like passport number)

The way I saw it was to generate a unique key hash(function dedupe rule)
and store it part of the signature

Rationale to do dedupe real-time :
You put a unique key sql constraint and done ;l

**Comment by tttp** [comment]
The issues of storing dedupe : ghosting become more complicated, and the
"useful" signal is quite weak imo

Where I am not sure is how to handle duplicate with different consents (eg
either optout then optin, or optin on different pages with different orgs)

**Comment by marcinkoziej** [comment]
Ghosting: We do not ghost, if we don't store the data :man_shrugging: 

What is "useful" signal ?

Dedupe with different data → I was also thinking about this. What strategies should we have. Also for silly things like a 2 signatures with different comments. Should we just drop the second one? Or concatenate? 
With opt-ins, should we ignore the second opt-in, because we "are no longer interested" in the duplicated signature and associated consent, and assume user must manage their optin status by different means (member portal, mailing footer link...). 
Or should we be even a bit cunning and accept the second signature if it's an opt-in, and discard the first one? Or keep two, but maximize opt-in rate for the org?

**Comment by tttp** [comment]
Very valid questions about duplicates that have different comments or optin consents ;(

I'm going to walk around them by saying that if the data is encrypted, we won't know if the comment was of wasn't different, so we can't do anything smart about it anyway.

As of the duplicate, let's move back this discussion on #4

**Pull request merged**
